apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-dev-scheduler
  labels:
    app: airflow-scheduler
    chart: airflow-0.0.1
    release: airflow-dev
    heritage: Helm
spec:
  selector:
    matchLabels:
      app: airflow-scheduler
      release: airflow-dev
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 100%
  template:
    metadata:
      annotations:
        checksum/config: 9a7edf8812918ff404ff3a682f054c88b0b1129e66801b9a8e58ec526d99ed74
        configmap.fabric8.io/update-on-change: "airflow-dev-env"
      labels:
        app: airflow-scheduler
        release: airflow-dev
    spec:
      securityContext:
        fsGroup: 1000
      restartPolicy: Always
      containers:
      - name: git-sync
        image: k8s.gcr.io/git-sync:v3.0.1
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: airflow-dev-dags
            mountPath: /git
        env:
          - name: GIT_SYNC_REPO
            value: https://github.com/Jackjaps/airflow.git
          - name: GIT_SYNC_BRANCH
            value: master
          - name: GIT_SYNC_ROOT
            value: /git
          - name: GIT_SYNC_DEST
            value: repo
          - name: GIT_SYNC_USERNAME
            valueFrom:
              secretKeyRef:
                name: git
                key: GIT_SYNC_USERNAME
          - name: GIT_SYNC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: git
                key: GIT_SYNC_PASSWORD
      - name: scheduler
        image: jacoboleguizamo/airflow:latest
        imagePullPolicy: IfNotPresent
        args: ["scheduler"]
        envFrom:
        - secretRef:
            name: airflow-dev-env
        env:
        - name: AIRFLOW_KUBE_NAMESPACE
          valueFrom:
           fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: airflow-config
          mountPath: /usr/local/airflow/airflow.cfg
          subPath: airflow.cfg
        - name: airflow-dev-dags
          mountPath: /usr/local/airflow/dags
        - name: airflow-logs
          mountPath: /usr/local/airflow/logs
      volumes:
        - name: airflow-logs
          persistentVolumeClaim:
            claimName: airflow-dev-logs  
        - name: airflow-config
          configMap:
            name: airflow-dev-config
        - name: airflow-dev-dags
          emptyDir: {}
