---
# Source: airflow/templates/webserver.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-dev-web
  labels:
    app: airflow-web
    chart: airflow-0.0.1
    release: airflow-dev
    heritage: Helm
spec:
  replicas: 1
  strategy:
    # Smooth rolling update of the Web UI
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: airflow-web
      release: airflow-dev
  template:
    metadata:
      annotations:
        checksum/config: 9a7edf8812918ff404ff3a682f054c88b0b1129e66801b9a8e58ec526d99ed74
        configmap.fabric8.io/update-on-change: "airflow-dev-env"
      labels:
        app: airflow-web
        release: airflow-dev
    spec:
      securityContext:
        fsGroup: 1000
      restartPolicy: Always
      initContainers:
      - name: "init-airflow"
        image: jacoboleguizamo/airflow:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: airflow-config
            mountPath: /usr/local/airflow/airflow.cfg
            subPath: airflow.cfg
          - name: init-airflow
            mountPath: /usr/local/init-airflow.sh
            subPath: init-airflow.sh
        envFrom:
          - secretRef:
              name: airflow-dev-env
        command:
          - "bash"
        args:
          - "-cx"
          - "bash /usr/local/init-airflow.sh"
      containers:
      - name: git-sync
        image: k8s.gcr.io/git-sync:v3.0.1
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: airflow-dags
            mountPath: /git
        env:
          - name: GIT_SYNC_REPO
            value: https://github.com/Jackjaps/airflow.git
          - name: GIT_SYNC_BRANCH
            value: master
          - name: GIT_SYNC_ROOT
            value: /git
          - name: GIT_SYNC_DEST
            value: repo
          - name: GIT_SYNC_WAIT
            value: "60"
          - name: GIT_SYNC_USERNAME
            valueFrom:
              secretKeyRef:
                name: git
                key: GIT_SYNC_USERNAME
          - name: GIT_SYNC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: git
                key: GIT_SYNC_PASSWORD
      - name: nginx
        image: nginx
        imagePullPolicy: IfNotPresent
        ports:
          - name: nginx
            containerPort: 80
        volumeMounts:
          - name: nginx
            mountPath: /etc/nginx/conf.d/default.conf
            subPath: nginx.conf
        readinessProbe:
          initialDelaySeconds: 5
          timeoutSeconds: 5
          periodSeconds: 5
          httpGet:
            path: /health
            port: 80
        livenessProbe:
          initialDelaySeconds: 5
          timeoutSeconds: 5
          failureThreshold: 5
          httpGet:
            path: /health
            port: 80
      - name: webserver
        image: jacoboleguizamo/airflow:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: webserver
          containerPort: 8080
        args: ["webserver"]
        envFrom:
          - secretRef:
              name: airflow-dev-env
        env:
        - name: AIRFLOW_KUBE_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        # - name: FORWARDED_ALLOW_IPS
        #   value: "*"
        volumeMounts:
        - name: airflow-config
          mountPath: /usr/local/airflow/airflow.cfg
          subPath: airflow.cfg
        - name: webserver-config
          mountPath: /usr/local/airflow/webserver_config.py
          subPath: webserver_config.py
        - name: airflow-logs
          mountPath: /usr/local/airflow/logs
        - name: airflow-dags
          mountPath: /usr/local/airflow/dags
        readinessProbe:
          initialDelaySeconds: 5
          timeoutSeconds: 5
          periodSeconds: 5
          httpGet:
            path: /health
            port: 8080
        livenessProbe:
          initialDelaySeconds: 5
          timeoutSeconds: 5
          failureThreshold: 5
          httpGet:
            path: /health
            port: 8080
      volumes:
      - name: airflow-logs
        persistentVolumeClaim:
          claimName: airflow-dev-logs
      - name: airflow-config
        configMap:
          name: airflow-dev-config
      - name: webserver-config
        secret:
          secretName: webserver-config
      - name: init-airflow
        configMap:
          name: airflow-dev-init
      - name: nginx
        configMap:
          name: airflow-dev-nginx
      - name: airflow-dags
        emptyDir: {}
