apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-logs-pv
  labels:
    app: {{ template "airflow.name" . }}
    chart: {{ template "airflow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/jacobomunoz/Documents/ingenieria/kubernetes/airflow-kube-helm/airflow/logs"
---
{{- if and .Values.airflow.dags.persistence.enabled (not .Values.airflow.dags.persistence.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "airflow.fullname" . }}-dags
  labels:
    app: {{ template "airflow.name" . }}
    chart: {{ template "airflow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:
    - {{ .Values.airflow.dags.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.airflow.dags.persistence.size | quote }}
{{- if .Values.airflow.dags.persistence.storageClass }}
{{- if (eq "-" .Values.airflow.dags.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.airflow.dags.persistence.storageClass }}"
{{- end }}
{{- end }}
{{- end }}

{{- if (not .Values.airflow.logs.persistence.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "airflow.fullname" . }}-logs
  labels:
    app: {{ template "airflow.name" . }}
    chart: {{ template "airflow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:
    - {{ .Values.airflow.logs.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.airflow.logs.persistence.size | quote }}
  selector:
    matchLabels:
      app: {{ template "airflow.name" . }}
      chart: {{ template "airflow.chart" . }}
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
#  {{- if .Values.airflow.logs.persistence.storageClass }}
#  {{- if (eq "-" .Values.airflow.logs.persistence.storageClass) }}
#  storageClassName: ""
#  {{- else }}
#  storageClassName: "{{ .Values.airflow.logs.persistence.storageClass }}"
#  {{- end }}
#  {{- end }}
#  {{- end }}


#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: dev-logs-pv
#  labels:
#    app: airflow
#    chart: airflow-0.0.1
#    release: dev
#    heritage: Helm
#spec:
#  capacity:
#    storage: 10Gi
#  accessModes:
#    - ReadWriteMany
#  persistentVolumeReclaimPolicy: Retain
#  azureFile:
#    secretName: azure-secret
#    shareName: airflowdisk
#    readOnly: false
#---
#kind: PersistentVolumeClaim
#apiVersion: v1
#metadata:
#  name: dev-logs
#  labels:
#    app: airflow
#    chart: airflow-0.0.1
#    release: dev
#    heritage: Helm
#  annotations:
#    volume.beta.kubernetes.io/storage-class: ""
#spec:
#  accessModes:
#    - ReadWriteMany
#  resources:
#    requests:
#      storage: 10Gi
#  selector:
#    matchLabels:
#      usage: airflowdisk

